### ISSUE TITLE
bugs in the code 

### ISSUE THREAD

**Issue by eriche2016** [erogol/seg-torch#2]
Thanks for sharing the excellent work.  In camvid.lua file,  I think it is better to remove self.dir  or set it to be nil.
https://github.com/erogol/seg-torch/blob/d4ce8121386b1d165545a0f7f2bc4884f818ae51/data/camvid.lua#L14
because it will give us the wrong directory where the image data sits., which will be:
```
self.dir/self.dir/sub_path_to_images. 
```
according to the `line` in 
https://github.com/erogol/seg-torch/blob/d4ce8121386b1d165545a0f7f2bc4884f818ae51/data/custom-gen.lua#L33
variable `line`(which represents path) will contain self.dir as its prefix substring

**Comment by erogol** [comment]
Thanks for kind words :). 
I don't think there is a problem.The line 14 is used as a prefix to load images in realtime. That same prefix is given at [line 59](https://github.com/erogol/seg-torch/blob/d4ce8121386b1d165545a0f7f2bc4884f818ae51/data/custom-gen.lua#L59 )

**Comment by eriche2016** [comment]
sorry, I should refer you [line 35](https://github.com/erogol/seg-torch/blob/d4ce8121386b1d165545a0f7f2bc4884f818ae51/data/camvid-gen.lua#L35), as i said, variable line(which represents path) will contain self.dir(which also is opt.datapath) as its prefix substring. so [here](https://github.com/erogol/seg-torch/blob/d4ce8121386b1d165545a0f7f2bc4884f818ae51/data/camvid.lua#L25) will cause an error, because imagePath already contains opt.datapath

**Comment by erogol** [comment]
Now I merged your pull request :+1:
