### ISSUE TITLE
Segnet output/target dimensions

### ISSUE THREAD

**Issue by rracinskij** [erogol/seg-torch#5]
Hi,
thank you for such a great work!
Could you please explain the required dimensionality of outputs and targets? Segnet model input is `[batchSize, numChannels, H, W] `and the output is `[batchSize, numClasses, H, W]`. But `cudnn.SpatialCrossEntropyCriterion()` requires the target to be of size `[batchSize, H, W]`. So it looks like that the model outputs `numClasses` separate masks for each class while the criterion expects a single mask with all the classes within it.
I can't get through this issue while reproducing the model with a toy example.

**Comment by eriche2016** [comment]
check [here](https://github.com/erogol/seg-torch/blob/master/train.lua#L79), the output of the model will be transposed to bz x H x W x numClasses, which is a probability distribution map.

**Comment by eriche2016** [comment]
check [here](https://github.com/soumith/cudnn.torch/blob/master/SpatialCrossEntropyCriterion.lua#L14), the criterion requires model output be of size `[batchSize, numClasses, H, W]`

**Comment by rracinskij** [comment]
Thank you for a prompt reply. So, for future reference - inputs are `[batchSize, numChannels, H, W]`, outputs are `[batchSize, numChannels, H, W]` tensors with separate dimension for each class and targets are `[batchSize, H, W]` tensors with all the classes encoded in the same dimension?

**Comment by eriche2016** [comment]
Yes, for the model output, each spatial location will be  a probability distribution of predefined classes.

**Comment by rracinskij** [comment]
Thanks a lot!
